### ISSUE TITLE
Records position only sporadically

### ISSUE THREAD

**Issue by TjrGithub** [bfabiszewski/ulogger-android#7] opened 2017-04-03 13:03 UTC
Hi,
I've left mulogger run continuously since its release on FDroid, at the 1 minute or 10 seconds refresh intervals. Unfortunately, it records position values only for a fraction of the times it should, especially when the phone is not in use.

I've already ruled out filtering (minimum accuracy, minimum movment etc) -- because all measurements are much better than 5km in my area and I left the phone at home. Disabling automatic battery optimizations made things worse on the one night I tried.

I believe this is the same as the known, difficult problem caused by overzealous power management. Tiny Travel Tracker might give plenty of inspirations what solutions do not work. On the other hand, GPX recording by the Osmand plugin has never failed me, but it is also very heavy on the battery.

https://f-droid.org/repository/browse/?fdfilter=tiny+travel+tracker&fdid=com.rareventure.gps2

https://f-droid.org/repository/browse/?fdfilter=osmand&fdid=net.osmand.plus

Attached is the database dump of time stamps. Please let me know what you'd need from the logfiles -- I'd prefer not to publish everything from a very long time span (and audit it for sensitive information beforehand).

Thank you, it feels great to work with a responsive developer, even if I'm just a lowly bug-reporter.

[ulogger.db.txt](https://github.com/bfabiszewski/ulogger-android/files/890101/ulogger.db.txt)

Version info, everything from FDroid: ulogger 1.0 and 1.1 (upgraded as soon as published). MicroG 0.2.4 stable, backends LocalGsmNlpBackend + LocalWifiNlpBackend + OpenBmapNlpBackend current stable versions with current offline database.
Android 6.0.1 slimrom. Latest XPrivacy and XPosed, no restrictions on ulogger.

**Comment by TjrGithub** [comment] 2017-04-04 17:22
Addendum: I found out I cannot say after all whether Tiny Travel Tracker gets the wakeup / power management right, for unrelated reasons. In any case, TTT did plenty of experiments on this topic.

**Comment by bfabiszewski** [comment] 2017-04-04 18:12
Looking at android [LocationManagerService](https://github.com/android/platform_frameworks_base/blob/master/services/core/java/com/android/server/LocationManagerService.java#L2186) it seems that it will not broadcast location if the device is not moving. It also means that minimum distance cannot be set to zero. I will try to cheat and change 0 to 0.01 or so. This may help, but there still will be cases when there will be no updates.
I could of course wake up the device every x seconds and force new location update, but that is something I would like to avoid. This would mean more battery usage. 
Logging my tracks I never set distance to "no minimum". If there are no new positions in the log I assume the device is not moving.
I will have to think about it and test more.

**Comment by TjrGithub** [comment] 2017-04-05 13:37
Hmm, as I read the code, it falls through to true at the end of the function if you set the minimum distance to zero, i.e. 0 is a perfectly valid minimum distance.

The network location backends aren't perfect - the position jumps around randomly depending on which neighbors' wifis happen to appear in the scan, or which of the several cell towers the phone is connecting to. I don't set a minimum distance because I'd like to average such fluctuations away, and/or get a feel for their magnitude.

**Comment by bfabiszewski** [comment] 2017-04-05 14:55
You are right, I misunderstood the logic. I will do some tests to see if I can reproduce your issue. 
In the meantime please repeat the tests with the newest version. 
There are some delays on f-droid part, but I hope the new version will be available soon.

**Comment by nmezheri** [comment] 2017-04-07 16:33
I noticed the delays on f-droid, and I had to buid the app on my own (by the way it worked).
On the other side may be have the apk here in guithub in addition to f-droid, ex.: https://github.com/ukanth/afwall/releases

**Comment by bfabiszewski** [comment] 2017-04-10 13:09
I did short test with only network provider enabled. Wifi was disabled on the device, so the only source of location was gsm network. Everything worked as expected. I set 1 minute time window and no minimum distance. I left it running for an hour and not a single update was lost, except that they all were above accuracy limit (500 m).

It was on µlogger 1.3, old android 2.3.6. Your problem must be related to different nlp backends on your device. You may try to get some more information by [turning debugging on](https://github.com/bfabiszewski/ulogger-android/blob/master/app/src/main/java/net/fabiszewski/ulogger/Logger.java#L17) and rebuilding µlogger. 

For me it will be difficult to reproduce your issue as I don't have any device that I can use with your setup and it will not work in emulator.

```
04-10 14:22:42.270 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location changed: Location[mProvider=network,mTime=1491826962249,mLatitude=...]
04-10 14:22:42.270 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location accuracy above limit: 848.0 > 500]
04-10 14:23:42.260 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location changed: Location[mProvider=network,mTime=1491827022256,mLatitude=...]
04-10 14:23:42.260 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location accuracy above limit: 848.0 > 500]
04-10 14:24:42.259 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location changed: Location[mProvider=network,mTime=1491827082262,mLatitude=...]
04-10 14:24:42.259 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location accuracy above limit: 848.0 > 500]
04-10 14:25:42.290 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location changed: Location[mProvider=network,mTime=1491827142283,mLatitude=...]
04-10 14:25:42.290 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location accuracy above limit: 848.0 > 500]
04-10 14:26:42.319 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location changed: Location[mProvider=network,mTime=1491827202308,mLatitude=...]
04-10 14:26:42.319 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location accuracy above limit: 848.0 > 500]
04-10 14:27:42.350 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location changed: Location[mProvider=network,mTime=1491827262344,mLatitude=...]
04-10 14:27:42.350 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location accuracy above limit: 848.0 > 500]
04-10 14:28:42.340 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location changed: Location[mProvider=network,mTime=1491827322331,mLatitude=...]
04-10 14:28:42.340 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location accuracy above limit: 848.0 > 500]
04-10 14:29:42.349 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location changed: Location[mProvider=network,mTime=1491827382346,mLatitude=...]
04-10 14:29:42.349 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location accuracy above limit: 848.0 > 500]
04-10 14:30:42.370 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location changed: Location[mProvider=network,mTime=1491827442359,mLatitude=...]
04-10 14:30:42.370 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location accuracy above limit: 848.0 > 500]
04-10 14:31:42.390 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location changed: Location[mProvider=network,mTime=1491827502377,mLatitude=...]
04-10 14:31:42.390 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location accuracy above limit: 848.0 > 500]
04-10 14:32:42.400 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location changed: Location[mProvider=network,mTime=1491827562393,mLatitude=...]
04-10 14:32:42.400 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location accuracy above limit: 848.0 > 500]
04-10 14:33:42.420 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location changed: Location[mProvider=network,mTime=1491827622412,mLatitude=...]
04-10 14:33:42.420 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location accuracy above limit: 848.0 > 500]
04-10 14:34:42.429 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location changed: Location[mProvider=network,mTime=1491827682433,mLatitude=...]
04-10 14:34:42.429 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location accuracy above limit: 848.0 > 500]
04-10 14:35:42.469 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location changed: Location[mProvider=network,mTime=1491827742461,mLatitude=...]
04-10 14:35:42.469 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location accuracy above limit: 848.0 > 500]
04-10 14:36:42.480 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location changed: Location[mProvider=network,mTime=1491827802475,mLatitude=...]
04-10 14:36:42.480 5918-5918/net.fabiszewski.ulogger D/LoggerService: [location accuracy above limit: 848.0 > 500]
...
```

**Comment by bfabiszewski** [comment] 2017-04-10 13:14
Regarding f-droid builds we are affected by [this issue](https://gitlab.com/fdroid/admin/issues/23). I hope it will be fixed soon. If it won't I will provide my own builds. I have not done it yet because it introduces incompatibility, as f-droid builds are signed with different key (users have to uninstall app each time they switch source).

**Comment by TjrGithub** [comment] 2017-04-10 19:05
I'm more than happy to test things, and I can deal with un- and reinstalling.

Would you please provide such a debug build? (Unfortunately, my computer cannot run Android Studio: 32bit, disk space, etc.)

Also, would you please provide a gnupg public key? Because the logcat of the microg network location services is also relevant, but I'm not comfortable broadcasting where I live.

**Comment by bfabiszewski** [comment] 2017-04-11 11:28
Debug build for [latest version](https://github.com/bfabiszewski/ulogger-android/tree/b38e57f34ac025aaaf7ee6ec3b383d9a72d3e4fd): 

[app-debug.apk.zip](https://github.com/bfabiszewski/ulogger-android/files/913007/app-debug.apk.zip)



[GPG key](https://sks-keyservers.net/pks/lookup?op=vindex&search=fabiszewski.net)

**Comment by bfabiszewski** [comment] 2017-05-04 06:48
I am going to close this. Please reopen if you have more input.

**Closed by bfabiszewski** 2017-05-04 06:48 UTC
