### ISSUE TITLE
No logging in background under Android 11

### ISSUE THREAD

**Issue by carelinus** [bfabiszewski/ulogger-android#95] opened 2021-01-06 21:07 UTC
In Android 11, the way location requests are approved has apparently changed. Unfortunately, ulogger lacks the option for constant location request in the system menu under Android 11, so logging is unfortunately only working when the display is on and in the foreground.

**Comment by bfabiszewski** [comment] 2021-01-07 10:18
Thanks for the report. 
I thought there are no new permissions needed. I'll check it on emulator.

**Comment by carelinus** [comment] 2021-01-07 10:27
Thank you for looking into this. If I can be of help (i.e. with testing) please let me know.

**Comment by bfabiszewski** [comment] 2021-01-07 11:37
Make sure to disable battery optimization for µlogger. Otherwise the application may be killed when in background.

**Comment by carelinus** [comment] 2021-01-07 11:48
That was also my first thought, but battery optimization is already disabled for µlogger. The app also keeps running (including notification), it just doesn't log unless the screen is on and the app is in the foreground.


Maybe this gives a hint at the cause of the problem?:
[https://medium.com/swlh/request-location-permission-correctly-in-android-11-61afe95a11ad](https://medium.com/swlh/request-location-permission-correctly-in-android-11-61afe95a11ad
)

And in the SDK documentation:
[https://developer.android.com/about/versions/11/privacy/location](https://developer.android.com/about/versions/11/privacy/location)

**Comment by carelinus** [comment] 2021-01-13 07:24
I can confirm (tested on an Android 11 phone) that the following diff fixes the issue (for the most part):

```
diff --git a/app/src/main/AndroidManifest.xml b/app/src/main/AndroidManifest.xml
index 0a6474b..d4f3945 100644
--- a/app/src/main/AndroidManifest.xml
+++ b/app/src/main/AndroidManifest.xml
@@ -14,6 +14,8 @@
     <uses-permission android:name="android.permission.WAKE_LOCK" />
     <!-- For foreground services API >= 28 -->
     <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
+    <!-- Required only when requesting background location access on Android 10 (API level 29) and higher. -->
+    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
     <!-- For location API >= 21 -->
     <uses-feature android:name="android.hardware.location.gps" android:required="false" />
     <uses-feature android:name="android.hardware.location.network" />
```

However the user still needs to know that the new option has to be chosen manually, see [this documentation](https://developer.android.com/training/location/permissions#background-dialog-target-android-11) for details.

**Comment by bfabiszewski** [comment] 2021-01-13 07:57
Sorry, I haven't had time yet to work on it.
Thanks for the research! Seems we really need this permission, even for foreground service.
I'll try to fix it soon.

**Comment by bfabiszewski** [comment] 2021-01-13 08:14
From what I read we should be able to continue using foreground location without additional permissions. 
It says:

> The system considers your app to be using foreground location if a feature of your app accesses the device's current location in one of the following situations:
> - An activity that belongs to your app is visible.
> - Your app is running a foreground service. When a foreground service is running, the system raises user awareness by showing a persistent notification. Your app retains access when it's placed in the background, such as when the user presses the Home button on their device or turns their device's display off.

The second case is ours.
Maybe something changed in relation to foreground services.
I've already implemented several changes that address deprecated API in Android 11 in my local branch. I yet need to find some free time to make tests on emulator.

**Comment by bfabiszewski** [comment] 2021-01-13 08:17
What is the device your are testing on?

**Comment by carelinus** [comment] 2021-01-13 08:28
I'm testing on an OnePlus 8 Pro device under Android 11.

I only added the above mentioned lines to the manifest, resulting in the appearance of the "allow always" option under location settings:

![Screenshot](https://user-images.githubusercontent.com/36591699/104425828-6ba43d80-5581-11eb-973d-a7a38184a11a.jpg)

Everything seems to work fine now (after manually selecting that new option).

**Comment by bfabiszewski** [comment] 2021-01-13 08:35
And what happens if you choose second option, "only while using the app"?

**Comment by carelinus** [comment] 2021-01-13 08:45
Then logging only works when the display is active in the foreground, which was the original issue.

The second option was already available without changing the manifest file. The modification only adds the first option.

**Comment by bfabiszewski** [comment] 2021-01-13 22:48
I think the problem might be caused by requesting location updates before bringing service forward. 
I added a [quick fix](https://github.com/bfabiszewski/ulogger-android/commit/702633ec73e71bf367676c799831ea45f23c8284) to [android_11 branch](https://github.com/bfabiszewski/ulogger-android/tree/android_11). The other changes on that branch just fix some deprecation issues.
Could you check if it allows logging in the background without adding `ACCESS_BACKGROUND_LOCATION` permission?

**Comment by carelinus** [comment] 2021-01-14 09:53
In a short test (so far only indoors) this seems to work as well, at least point were logged while the app was not in foreground and the display was off.

**Comment by carelinus** [comment] 2021-01-16 15:54
It might be unrelated, but somehow I can't get the upload to work in this build. It says "Upload started" but nothing happens and the number of locally stored points stays the same. Are there any changes in that branch regarding uploading?

**Comment by bfabiszewski** [comment] 2021-01-16 19:27
Thanks for testing!
I fixed uploading. Should work now.
Does adding waypoints work on Android 11? When testing make sure to pull latest commits as I made changes to waypoint handling.

**Comment by carelinus** [comment] 2021-01-16 21:01
Nice, uploading works again. Also adding a waypoint works. However, I can only add an image from the gallery. When trying to take a new picture, an error is given: "You must accept permission for writing photo to external storage".
No storage permission is requested though. Also in the settings screen no storage permission is available to grant.

**Comment by bfabiszewski** [comment] 2021-01-16 21:54
Good catch. Should be fixed now.

**Comment by carelinus** [comment] 2021-01-16 22:07
Yes! Thank you, it's working now.

**Comment by bfabiszewski** [comment] 2021-01-17 15:33
Great. I still want to introduce some changes before I release this version.
I'll let you know when I push something new. Maybe you will be able to make some testing.
Thanks for help.

**Comment by carelinus** [comment] 2021-01-18 09:21
Sure, let me know if there is anything to test. Thanks for fixing the problems quickly.

**Comment by bfabiszewski** [comment] 2021-01-23 20:59
I pushed some commits. I tested it on emulator and didn't find any problems.
You may test in on you device if you wish.
I mainly changed the code related to waypoint logging.
Background location permission is not needed for normal application usage. But it is required when logging is started automatically without user interaction, for example from tasker or autostarted on system boot.

**Comment by carelinus** [comment] 2021-01-24 09:04
I've installed 301eb0d and will do some testing later. First (really minor) issue I noticed: the message instructing about allowing background location is in English with "Immer zulassen" ("Allow all the time") in German (device language).

**Comment by bfabiszewski** [comment] 2021-01-24 14:24
Good catch. The problem is with partially translated languages. I fixed it with a workaround.

**Comment by bfabiszewski** [comment] 2021-01-27 20:29
Thank you very much for all your help on Android 11 branch.
I am closing this issue now. 
If you find any new problems, please open new report.

**Closed by bfabiszewski** 2021-01-27 20:29 UTC
